### PR TITLE
Handle SIGWINCH, update std code and fix typos

### PR DESCRIPTION
**Pull request by l0kod**
This series add the SIGWINCH signal. It is received when resizing a terminal (TTY) window.

I also updated a bit the code :)

### CODE REVIEW

**Comment by BurntSushi** [comment]
@l0kod I decided to merge #11 since it contained a lot more signals, which I think caused a conflict here.

Sorry about being so late to respond, this PR went under my radar. If you'd like to rebase on current master, I'd be happy to merge. Thanks. :-)

**Comment by l0kod** [comment]
Done! An update on crates.io would be great. :)

**Comment by BurntSushi** [comment]
Awesome! Thanks!

**Comment by BurntSushi** [comment]
I've put `0.1.7` on crates.io. Thanks again!

**Pull request merged**
